Tests/Stuff/FooTest.cpp, Line 42

Expected Exception Type:
[std::runtime_error]
A happy runtime error!

=======================================

