Check started:


Critical Failure:
Error -- Unexpected Exception:
This is bad

Exception thrown during last check
Last Recorded Message:

Throw during check
[sequoia::testing::(anonymous namespace)::foo]
